# -*- coding:utf-8 -*-

class Const():
	ISBN_MAX_LENGTH = 13
	ISBN_MIN_LENGTH = 13
	BOOK_NAME_MAX_LENGTH = 100
	BOOK_NAME_MIN_LENGTH = 1
	AUTHOR_NAME_MAX_LENGTH = 50
	AUTHOR_NAME_MIN_LENGTH = 1
	PRESS_NAME_MAX_LENGTH = 100
	PRESS_NAME_MIN_LENGTH = 1
	PASSWD_MIN_LENGTH = 6
    	PASSWD_MAX_LENGTH = 64
    	PASSWD_SALT = "j#$E&s(SI$e$sZ^^e*F%aN!yin#D+&I=r)&A"
